# Generated by Django 3.1.6 on 2021-02-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_salesorder_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='product',
            new_name='products',
        ),
    ]
